apiVersion: apps/v1
kind: Deployment
metadata:
  name: speed-sport-souvenirs
  namespace: speed-sport-souvenirs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speed-sport-souvenirs
  template:
    metadata:
      labels:
        app: speed-sport-souvenirs
    spec:
      containers:
        - name: speed-sport-souvenirs
          image: t0dorov/speed_sports_souvenirs:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DATABASE_NAME
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DATABASE_PORT
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DATABASE_PASSWORD
            - name: DJANGO_SUPERUSER_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DJANGO_SUPERUSER_USERNAME
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: django-config
                  key: DJANGO_SUPERUSER_EMAIL
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: DJANGO_SUPERUSER_PASSWORD
