# Generated by Django 4.1.7 on 2023-06-19 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories'},
        ),
    ]
