# Generated by Django 4.1.7 on 2023-06-25 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_team_alter_userinfo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='series',
        ),
        migrations.AddField(
            model_name='category',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, to='base.team'),
        ),
        migrations.AddField(
            model_name='product',
            name='racing_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_by_team', to='base.racingseries'),
        ),
        migrations.AddField(
            model_name='product',
            name='teams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='base.team'),
        ),
        migrations.AddField(
            model_name='racingseries',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, to='base.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='racing_series',
            field=models.ManyToManyField(blank=True, null=True, to='base.racingseries'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='base.category'),
        ),
    ]
