# Generated by Django 4.1.7 on 2023-06-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_team_racing_series_team_racing_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='racingseries',
            name='teams',
        ),
    ]
