# Generated by Django 4.1.7 on 2023-06-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_category_teams_remove_racingseries_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='teams',
            new_name='team',
        ),
    ]
