# Generated by Django 4.1.7 on 2023-06-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cc',
            options={'verbose_name': 'Credit Card', 'verbose_name_plural': 'Credit Cards'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
