# Generated by Django 4.1.7 on 2023-06-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_cart_user_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CC',
        ),
    ]
